# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    # Enable CSRF protection for forms
    csrf_protection: true

    # Enable session management and set session lifetime (10 mins)
    session:
        enabled: true
        cookie_lifetime: 600       # Lifetime in seconds (10 minutes)
        gc_maxlifetime: 600          # Garbage collection max lifetime (10 minutes)

    # Optional: ESI and Fragments for advanced caching techniques
    # esi: true
    # fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file